# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    - run : | 
          mkdir -p ~/.ssh
          ssh-keyscan -t ecdsa github.com > ~/.ssh/known_hosts
          ssh-keyscan -t ecdsa ${{secrets.EUREKA_HOST}} > ~/.ssh/known_hosts
          echo "${{ secrets.EUREKA_PK }}" > ~/.ssh/id_ecdsa
          chmod 400 ~/.ssh/id_ecdsa
          ls -lhart ~/.ssh/id_ecdsa
          
          git remote add deploy ${{secrets.EUREKA_REPO}}
          git remote add github git@github.com:BrianKemboi/eureka.git
          
          git config --global user.name github-actions
          git config --global user.email actions@git.com
          git config --global pull.rebase true        
          
          git fetch --unshallow github main
          
          git push deploy main:master
          
